spring:
  profiles: mac
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@db202202032030_high?TNS_ADMIN=/Users/choi/dev/Wallet
    username: admin
    password: 1234
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  pid:
    file: /Users/choi/dev/boot.pid

mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8084
  servlet:
    session:
      timeout: 600
      tracking-modes: cookie

logging:
  level:
    root: info
  file:
    name: /Users/choi/dev/log/boot.log

file:
  dir: /Users/choi/dev/upload/

---

spring:
  profiles: window
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: jdbc:oracle:thin:@db202202032030_high?TNS_ADMIN=C:\\dev\\Wallet
    username: admin
    password: 1234
  datasource-sub:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://193.123.240.87:3306/mysql
    username: root
    password: 1234
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  pid:
    file: C:\\Users\\choi\\Desktop\\boot.pid

mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8084
  servlet:
    session:
      timeout: 600
      tracking-modes: cookie

logging:
  level:
    root: info
  file:
    name: C:\\Users\\choi\\Desktop\\boot.log

file:
  dir: C:\\dev\\upload\\

---

spring:
  profiles: cloud
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@db202202032030_high?TNS_ADMIN=/home/opc/dev/Wallet/
    username: admin
    password: 1234
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  pid:
    file: /home/opc/dev/boot.pid

mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8084
  servlet:
    session:
      timeout: 600
      tracking-modes: cookie

logging:
  level:
    root: warn
  file:
    name: /home/opc/dev/log/boot.log

file:
  dir: /home/opc/dev/upload/